export const NLU_REQUEST = 'NLU_REQUEST'
export const NLU_SUCCESS = 'NLU_SUCCESS'
export const NLU_FAILURE = 'NLU_FAILURE'

export const LOOKUP_LOCATION_REQUEST = 'LOOKUP_LOCATION_REQUEST'
export const LOOKUP_LOCATION_SUCCESS = 'LOOKUP_LOCATION_SUCCESS'
export const LOOKUP_LOCATION_FAILURE = 'LOOKUP_LOCATION_FAILURE'

export const ANALYZE_AND_LOOKUP_REQUEST = 'ANALYZE_AND_LOOKUP_REQUEST'
export const ANALYZE_AND_LOOKUP_SUCCESS = 'ANALYZE_AND_LOOKUP_SUCCESS'
export const ANALYZE_AND_LOOKUP_FAILURE = 'ANALYZE_AND_LOOKUP_FAILURE'
